import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
const source=stripTypeScriptTypes(readFileSync(new URL('../supabase/functions/owner-account/index.ts',import.meta.url),'utf8'));
const owner={id:'owner-id',role:'owner',login_email:'private@example.invalid',login_name:'nitwadee',display_name:'Owner',deleted_at:null};
async function invoke(body,options={}){
 let handler,profileReads=0;const calls=[],warnings=[];
 const fetch=async(url,init)=>{const parsed=new URL(url),payload=init.body?JSON.parse(init.body):null;calls.push({path:parsed.pathname,query:parsed.search,method:init.method,payload,token:init.headers.Authorization});let data,status=200;
 if(parsed.pathname.endsWith('/token')){data=options.wrongPassword?{message:'private auth error'}:{access_token:'temporary',refresh_token:'refresh',user:{id:options.mismatch?'other-id':owner.id},expires_in:3600};if(options.wrongPassword)status=400;}
 else if(parsed.pathname.endsWith('/recover')){if(options.recoverThrow)throw new Error('private network diagnostic');data=options.recoverFail?{message:'SMTP secret diagnostic'}:{};if(options.recoverFail)status=500;}
 else if(parsed.pathname.endsWith('/logout')){data={};}
 else if(parsed.pathname.endsWith('/user')&&init.method==='GET'){data=options.unauthenticated?null:{id:owner.id,email:owner.login_email};if(options.unauthenticated)status=401;}
 else if(parsed.pathname.endsWith('/user')){data=options.updateFail?{message:'sensitive error'}:{id:owner.id};if(options.updateFail)status=400;}
 else if(parsed.pathname.endsWith('/profiles')){profileReads++;if(options.secondProfileThrow&&profileReads===2)throw new Error('offline');if(options.lookupFail){status=500;data={message:'private db error'};}else if(init.method==='PATCH'){data=options.saveFail?[]:[{login_name:payload.login_name,display_name:'Owner'}];}else if(parsed.searchParams.has('or'))data=options.conflict?[{id:'office-id'}]:[];else data=options.missing||(options.secondProfileDisabled&&profileReads===2)?[]:[{...owner,...options.profile}];}
 else throw new Error('unexpected URL');return new Response(JSON.stringify(data),{status});};
 vm.runInNewContext(source,{Response,fetch,AbortSignal,TextEncoder,crypto:webcrypto,console:{warn:message=>warnings.push(message)},Deno:{env:{get:k=>({ALLOWED_ORIGINS:'https://po-thegrands.vercel.app',SUPABASE_URL:'https://example.invalid',SUPABASE_ANON_KEY:'anon',SUPABASE_SERVICE_ROLE_KEY:'service'}[k])},serve:fn=>handler=fn}});
 const r=await handler(new Request('https://example.invalid',{method:options.method||'POST',headers:{origin:options.origin||'https://po-thegrands.vercel.app',authorization:options.noBearer?'':'Bearer original','content-type':'application/json'},body:options.method==='OPTIONS'?undefined:JSON.stringify(body)}));return {status:r.status,body:r.status===204?null:await r.json(),calls,warnings};
}
const rename={action:'update-login-name',username:'Nitwadee',currentPassword:'old-password'};
for(const [label,opts,status] of [['office',{profile:{role:'office'}},403],['disabled',{missing:true},403],['forged bearer',{unauthenticated:true},401],['no bearer',{noBearer:true},401],['lookup failure',{lookupFail:true},503],['wrong password',{wrongPassword:true},400]])test(`reject ${label} before writes`,async()=>{const r=await invoke(rename,opts);assert.equal(r.status,status);assert.equal(r.calls.some(c=>['PATCH','PUT'].includes(c.method)),false);});
test('reject target/email/role injection',async()=>{for(const field of ['id','profile_id','email','role']){const r=await invoke({...rename,[field]:'anything'});assert.equal(r.status,400);assert.equal(r.calls.length,0);}});
test('reauth UUID mismatch denies mutation and cleans only temporary session',async()=>{const r=await invoke(rename,{mismatch:true});assert.equal(r.status,403);assert.equal(r.calls.some(c=>c.method==='PATCH'),false);assert.equal(r.calls.at(-1).query,'?scope=local');assert.equal(r.calls.at(-1).token,'Bearer temporary');});
test('alias collision fails before mutation and cleans reauth',async()=>{const r=await invoke(rename,{conflict:true});assert.equal(r.status,409);assert.equal(r.calls.some(c=>c.method==='PATCH'),false);assert.equal(r.calls.at(-1).token,'Bearer temporary');});
test('alias is normalized and updates only current owner login_name',async()=>{const r=await invoke(rename);assert.equal(r.status,200);const patch=r.calls.find(c=>c.method==='PATCH');assert.deepEqual(patch.payload,{login_name:'nitwadee'});assert.match(patch.query,/id=eq.owner-id/);assert.match(patch.query,/role=eq.owner/);assert.equal(r.calls.some(c=>c.method==='PUT'),false);assert.equal(r.calls.at(-1).token,'Bearer temporary');});
test('failed alias update has no false success and cleans reauth',async()=>{const r=await invoke(rename,{saveFail:true});assert.equal(r.status,409);assert.equal(r.calls.at(-1).query,'?scope=local');});
test('password update uses fresh token current_password and no admin changes',async()=>{const r=await invoke({action:'change-password',newPassword:'new-password',currentPassword:'old-password'});assert.equal(r.status,200);const put=r.calls.find(c=>c.method==='PUT');assert.equal(put.token,'Bearer temporary');assert.deepEqual(put.payload,{password:'new-password',current_password:'old-password'});assert.equal(r.calls.some(c=>c.method==='PATCH'),false);assert.equal(r.calls.at(-1).token,'Bearer temporary');});
test('failed password update cleans reauth and does not leak errors',async()=>{const r=await invoke({action:'change-password',newPassword:'new-password',currentPassword:'old-password'},{updateFail:true});assert.equal(r.status,400);assert.equal(JSON.stringify(r.body).includes('sensitive'),false);assert.equal(r.calls.at(-1).query,'?scope=local');});
test('short new password fails before reauthentication',async()=>{const r=await invoke({action:'change-password',newPassword:'12345',currentPassword:'old-password'});assert.equal(r.status,400);assert.equal(r.calls.some(c=>c.path.endsWith('/token')),false);});
test('public alias signin returns session with only safe Auth user ID',async()=>{const r=await invoke({action:'login',username:'Nitwadee',password:'password'});assert.equal(r.status,200);assert.equal(r.body.access_token,'temporary');assert.equal(JSON.stringify(r.body).includes('private@'),false);assert.deepEqual(r.body.user,{id:owner.id});});
test('office alias also signs in',async()=>{const r=await invoke({action:'login',username:'office',password:'password'},{profile:{role:'office'}});assert.equal(r.status,200);});
test('unknown alias and wrong password share failure and both call Auth',async()=>{const unknown=await invoke({action:'login',username:'unknown',password:'password'},{missing:true,wrongPassword:true});const wrong=await invoke({action:'login',username:'nitwadee',password:'password'},{wrongPassword:true});assert.equal(unknown.status,wrong.status);assert.deepEqual(unknown.body,wrong.body);assert.equal(unknown.calls.some(c=>c.path.endsWith('/token')),true);assert.match(unknown.calls.find(c=>c.path.endsWith('/token')).payload.email,/^missing-.*@invalid.local$/);});
test('alias lookup error fails closed and never sends credentials to guessed email',async()=>{const r=await invoke({action:'login',username:'nitwadee',password:'password'},{lookupFail:true});assert.equal(r.status,503);assert.equal(r.calls.some(c=>c.path.endsWith('/token')),false);});
test('CORS denies unapproved origin without backend calls',async()=>{const r=await invoke(rename,{origin:'https://evil.invalid'});assert.equal(r.status,403);assert.equal(r.calls.length,0);});

test('post-login profile network failure revokes newly created session',async()=>{const r=await invoke({action:'login',username:'nitwadee',password:'password'},{secondProfileThrow:true});assert.equal(r.status,503);assert.equal(r.calls.at(-1).query,'?scope=local');assert.equal(r.calls.at(-1).token,'Bearer temporary');});
test('login UUID mismatch revokes session and gives generic failure',async()=>{const r=await invoke({action:'login',username:'nitwadee',password:'password'},{mismatch:true});assert.equal(r.status,400);assert.equal(r.calls.at(-1).query,'?scope=local');});
test('oversized body without Content-Length is rejected before backend calls',async()=>{const r=await invoke({action:'login',username:'nitwadee',password:'x'.repeat(5000)});assert.equal(r.status,400);assert.equal(r.calls.length,0);});

test('owner disabled during reauthentication cannot update password and reauth is cleaned',async()=>{const r=await invoke({action:'change-password',newPassword:'new-password',currentPassword:'old-password'},{secondProfileDisabled:true});assert.equal(r.status,403);assert.equal(r.calls.some(c=>c.method==='PUT'),false);assert.equal(r.calls.at(-1).query,'?scope=local');});

test('six-character owner password is accepted',async()=>{const r=await invoke({action:'change-password',newPassword:'123456',currentPassword:'old-password'});assert.equal(r.status,200);assert.equal(r.calls.find(c=>c.method==='PUT').payload.password,'123456');});

test('recovery alias sends only to server owner email and trusted redirect without authentication',async()=>{const r=await invoke({action:'request-recovery',username:'Nitwadee'},{noBearer:true});assert.equal(r.status,200);assert.equal(r.body.success,true);const request=r.calls.find(c=>c.path.endsWith('/recover'));assert.deepEqual(request.payload,{email:owner.login_email});assert.equal(new URLSearchParams(request.query).get('redirect_to'),'https://po-thegrands.vercel.app/?view=recovery');assert.equal(request.token,'Bearer anon');assert.equal(JSON.stringify(r.body).includes(owner.login_email),false);assert.equal(JSON.stringify(r.body).includes(owner.id),false);});
test('recovery email lookup is exact active owner only',async()=>{const r=await invoke({action:'request-recovery',username:owner.login_email});assert.equal(r.status,200);const query=new URLSearchParams(r.calls[0].query);assert.equal(query.get('login_email'),'eq.'+owner.login_email);assert.equal(query.get('role'),'eq.owner');assert.equal(query.get('deleted_at'),'is.null');});
test('unknown disabled office and malformed recovery identifiers return same generic success',async()=>{const known=await invoke({action:'request-recovery',username:'Nitwadee'});for(const [username,options] of [['unknown',{missing:true}],['disabled',{missing:true}],['office',{profile:{role:'office'}}],['bad,(role.eq.owner)',{}]]){const r=await invoke({action:'request-recovery',username},options);assert.equal(r.status,200);assert.deepEqual(r.body,known.body);assert.equal(r.calls.some(c=>c.path.endsWith('/recover')),false);}});
test('recovery rejects client target email UUID or redirect override',async()=>{for(const field of ['email','profile_id','redirectTo','redirect_to','role']){const r=await invoke({action:'request-recovery',username:'Nitwadee',[field]:'attacker@example.invalid'});assert.equal(r.status,400);assert.equal(r.calls.length,0);}});
test('recovery lookup failure fails closed without private diagnostics',async()=>{const r=await invoke({action:'request-recovery',username:'Nitwadee'},{lookupFail:true});assert.equal(r.status,503);assert.equal(JSON.stringify(r.body).includes(owner.login_email),false);});
test('provider rejection or network failure shares unknown recovery response and logs only generic warning',async()=>{const unknown=await invoke({action:'request-recovery',username:'unknown'},{missing:true});for(const options of [{recoverFail:true},{recoverThrow:true}]){const r=await invoke({action:'request-recovery',username:'Nitwadee'},options);assert.equal(r.status,200);assert.deepEqual(r.body,unknown.body);assert.equal(r.warnings.length,1);assert.equal(JSON.stringify(r.warnings).includes(owner.login_email),false);assert.equal(JSON.stringify(r.warnings).includes('private'),false);assert.equal(JSON.stringify(r.warnings).includes('SMTP'),false);}});

test('recovery never modifies Auth user or profiles',async()=>{const r=await invoke({action:'request-recovery',username:'Nitwadee'});assert.equal(r.calls.some(c=>['PATCH','PUT'].includes(c.method)),false);assert.equal(r.calls.some(c=>c.path.endsWith('/token')),false);});
