import test from 'node:test';
import assert from 'node:assert/strict';
import {createPreviewService,deriveFinancials,isConfirmedPurchase} from '../dist/preview-workflow.js';
import {createPreviewFixtures} from '../dist/preview-fixtures.js';

class MemoryStorage{data=new Map();fail=false;getItem(key){return this.data.get(key)||null;}setItem(key,value){if(this.fail)throw Error('quota');this.data.set(key,String(value));}removeItem(key){this.data.delete(key);}}
const actors={owner:{id:'owner',role:'owner',display_name:'เจ้าของ'},office:{id:'preview-office',role:'office',display_name:'พนักงาน'},primary:{id:'primary',role:'primary',display_name:'ฝ่ายจัดซื้อ'},other:{id:'other',role:'office',display_name:'อีกคน'}};
const sample=(extra={})=>({department:'ครัว',name:'ของทดลอง',spec:'รุ่นมาตรฐาน',source:'ร้านตัวอย่าง',note:'',qty:'2',unit:'กล่อง',unit_price:'107',vat:true,payment_method:'credit',price_kind:'confirmed',...extra});
const baseMonth='2026-10';
function service(storage=new MemoryStorage(),fixtures=createPreviewFixtures()){return {storage,api:createPreviewService({storage,fixtures})};}
function act(api,po,action,{actor=actors.owner,itemId=po.items[0].id,reason='',confirmed=false,key=crypto.randomUUID()}={}){return api.run(po.id,action,{actor,itemId,reason,confirmed,key,expectedVersion:po.version});}
test('preview fixtures are synthetic, deterministic, fully normalized and cover required states',()=>{
 const one=createPreviewFixtures(),two=createPreviewFixtures();assert.deepEqual(one.map(p=>p.id),two.map(p=>p.id));
 for(const po of one){assert.ok(po.items.length);assert.ok(Number.isInteger(po.confirmed_purchase_cents));assert.ok(po.events.length);for(const item of po.items){assert.ok(item.id);assert.ok(item.department&&item.unit&&item.payment_method);assert.ok(['confirmed','estimated'].includes(item.price_kind));}}
 for(const state of ['pending','returned','rejected','budget_approved','approved','received'])assert.ok(one.some(po=>po.items.some(i=>i.state===state)));
 assert.ok(one.some(po=>po.items.filter(i=>i.state==='rejected').length===po.items.length));
});
test('create retries are stable, payload/actor changes conflict, author fields are required',()=>{
 const {api}=service(new MemoryStorage(),[]);const first=api.create([sample()],{actor:actors.office,poDate:`${baseMonth}-05`,key:'same'});const retry=api.create([sample()],{actor:actors.office,poDate:`${baseMonth}-05`,key:'same'});assert.deepEqual(retry,first);assert.throws(()=>api.create([sample({price_kind:'estimated'})],{actor:actors.office,poDate:`${baseMonth}-05`,key:'same'}),/รหัสคำสั่ง/);assert.throws(()=>api.create([sample({payment_method:''})],{actor:actors.office,poDate:`${baseMonth}-05`,key:'bad'}),/การชำระเงิน/);assert.throws(()=>api.create([sample({unit:''})],{actor:actors.office,poDate:`${baseMonth}-05`,key:'bad2'}),/หน่วย/);assert.throws(()=>api.create([sample({department:''})],{actor:actors.office,poDate:`${baseMonth}-05`,key:'bad3'}),/แผนก/);assert.equal(api.list(actors.office).length,1);
});
test('approval is per item; estimated budget must confirm and reapprove before receipt and invoice close',()=>{
 const {api}=service(new MemoryStorage(),[]);let po=api.create([sample({price_kind:'estimated'})],{actor:actors.office,poDate:`${baseMonth}-06`,key:'estimate'});assert.throws(()=>act(api,po,'approve'),/ราคาประมาณการ/);po=act(api,po,'approve_estimate');assert.equal(po.items[0].state,'budget_approved');assert.equal(po.budget_authorized_cents,21400);assert.equal(po.confirmed_purchase_cents,0);assert.throws(()=>act(api,po,'receive',{actor:actors.office,confirmed:true}),/อนุมัติแล้ว/);
 po=api.edit(po.id,po.items[0].id,sample({unit_price:'125',price_kind:'confirmed'}),{actor:actors.office,reason:'ยืนยันตามใบเสนอราคา',key:'confirm',expectedVersion:po.version,submit:true});assert.equal(po.items[0].state,'pending');assert.equal(po.items[0].price_kind,'confirmed');const audit=po.events.find(e=>e.action==='edit');assert.equal(audit.before.price_kind,'estimated');assert.equal(audit.after.price_kind,'confirmed');assert.equal(audit.before.unit_price,'107');assert.equal(audit.after.unit_price,'125');assert.equal(audit.delta_cents,3600);const submission=po.events.find(e=>e.action==='resubmit');assert.equal(submission.before.price_kind,'estimated');assert.equal(submission.after.price_kind,'confirmed');assert.equal(submission.delta_cents,3600);
 po=act(api,po,'approve');assert.equal(po.items[0].state,'approved');assert.throws(()=>act(api,po,'receive',{actor:actors.office}),/ยืนยันว่าได้รับ/);po=act(api,po,'receive',{actor:actors.office,confirmed:true});assert.equal(po.received_cents,25000);assert.equal(isConfirmedPurchase(po.items[0]),true);assert.throws(()=>act(api,po,'close',{confirmed:false}),/ยืนยันว่าได้รับใบกำกับ/);po=act(api,po,'close',{confirmed:true});assert.equal(po.status,'closed');assert.equal(po.confirmed_purchase_cents,25000);assert.throws(()=>act(api,po,'close',{confirmed:true}),/ปิดแล้ว/);
});
test('optional owner approval note is retained in the immutable audit event',()=>{
 const {api}=service(),po=api.load('preview-pending',actors.owner),approved=act(api,po,'approve',{itemId:'item-pending-a',reason:'ตรวจสอบราคาแล้ว'});const event=approved.events.find(row=>row.action==='approve'&&row.item_id==='item-pending-a');assert.equal(event.reason,'ตรวจสอบราคาแล้ว');
});
test('return/revision snapshots are immutable; refusal restores approval; edits record complete satang delta',()=>{
 const {api}=service();let po=api.load('preview-approved',actors.office),id='item-approved';const initial=api.load(po.id,actors.office).items.find(i=>i.id===id);const saved=structuredClone(initial.approved_snapshot);assert.throws(()=>act(api,po,'return_edit',{reason:' '}),/เหตุผล/);assert.deepEqual(api.load(po.id,actors.office),po);
 po=act(api,po,'return_edit',{reason:'ขอปรับจำนวน'});assert.equal(po.items.find(i=>i.id===id).state,'editing');const revised=api.edit(po.id,id,{...sample({unit_price:'999'}),price_kind:'confirmed'},{actor:actors.office,reason:'แก้จำนวนตามคำขอ',key:'revise',expectedVersion:po.version,submit:true});assert.equal(revised.items.find(i=>i.id===id).state,'pending');const editEvent=revised.events.find(e=>e.action==='edit');assert.equal(editEvent.before.total_cents,initial.total_cents);assert.equal(editEvent.after.total_cents,199800);assert.equal(editEvent.delta_cents,editEvent.new_amount_cents-editEvent.old_amount_cents);assert.deepEqual(revised.items.find(i=>i.id===id).approved_snapshot,saved);
 let approved=api.load(po.id,actors.office);approved=act(api,approved,'approve',{itemId:id});const authorized=approved.confirmed_purchase_cents;approved=act(api,approved,'request_revision',{actor:actors.office,itemId:id,reason:'ผู้ขายเปลี่ยนราคา'});assert.equal(approved.items.find(i=>i.id===id).state,'revision_requested');const paused=approved.confirmed_purchase_cents;assert.ok(paused<authorized);approved=act(api,approved,'refuse_revision',{reason:'คงอนุมัติราคาเดิม'});assert.equal(approved.items.find(i=>i.id===id).state,'approved');assert.equal(approved.confirmed_purchase_cents,authorized);
});
test('service rejects shortcut price confirmation, unchecked receipt and invalid author edits without audit/version changes',()=>{
 const {api}=service(),estimated=api.load('preview-estimated',actors.office);assert.throws(()=>api.run(estimated.id,'confirm_price',{actor:actors.office,itemId:'item-estimated',key:'shortcut',expectedVersion:estimated.version}),/แก้ไขข้อมูล/);let approved=api.load('preview-approved',actors.office),itemId='item-approved';assert.throws(()=>api.run(approved.id,'receive',{actor:actors.office,itemId,confirmed:false,key:'no-check',expectedVersion:approved.version}),/ยืนยันว่าได้รับ/);assert.equal(api.load(approved.id,actors.office).items.find(i=>i.id===itemId).state,'approved');let returned=api.load('preview-returned',actors.office);assert.throws(()=>api.edit(returned.id,'item-returned',sample({price_kind:'unsupported'}),{actor:actors.office,key:'bad-edit',expectedVersion:returned.version}),/เลือกว่าราคา/);assert.deepEqual(api.load(returned.id,actors.office),returned);
});
test('permissions, action cache identity and stale versions are enforced across service instances',()=>{
 const store=new MemoryStorage(),a=createPreviewService({storage:store,fixtures:createPreviewFixtures()}),b=createPreviewService({storage:store,fixtures:createPreviewFixtures()});const po=a.load('preview-pending',actors.office);assert.throws(()=>a.load(po.id,actors.other),/ไม่มีสิทธิ์/);assert.throws(()=>a.report(baseMonth,actors.owner),/ฝ่ายจัดซื้อหลัก/);assert.throws(()=>a.edit('preview-pending','item-pending-a',sample(),{actor:actors.primary,key:'forbidden',expectedVersion:1}),/ผู้สร้าง/);
 const current=a.load(po.id,actors.owner);const result=a.run(po.id,'approve',{actor:actors.owner,itemId:'item-pending-a',key:'approve-once',expectedVersion:current.version});assert.deepEqual(a.run(po.id,'approve',{actor:actors.owner,itemId:'item-pending-a',key:'approve-once',expectedVersion:current.version}),result);assert.throws(()=>a.run(po.id,'reject',{actor:actors.owner,itemId:'item-pending-a',reason:'ไม่ผ่าน',key:'approve-once',expectedVersion:current.version}),/รหัสคำสั่ง/);assert.throws(()=>b.run(po.id,'approve',{actor:actors.owner,itemId:'item-pending-est',key:'stale',expectedVersion:current.version}),/ข้อมูลเปลี่ยน/);
 const third=createPreviewService({storage:store,fixtures:[]});assert.deepEqual(third.load(po.id,actors.owner),result);
});
test('cached edit is bound to actor role and returned values cannot mutate persisted history',()=>{
 const {api}=service(),po=api.load('preview-pending',actors.office),editing=act(api,po,'return_edit',{reason:'ปรับรายการ',itemId:'item-pending-a'});const fields=sample({unit_price:'200',price_kind:'confirmed'});const saved=api.edit(po.id,'item-pending-a',fields,{actor:{id:'preview-office',role:'primary',display_name:'ฝ่ายจัดซื้อ'},reason:'ปรับแล้ว',key:'role-bound',expectedVersion:editing.version});assert.equal(saved.version,editing.version+1);assert.throws(()=>api.edit(po.id,'item-pending-a',fields,{actor:actors.office,reason:'ปรับแล้ว',key:'role-bound',expectedVersion:editing.version}),/รหัสคำสั่ง/);saved.items[0].name='caller mutation';saved.events[0].reason='caller mutation';const reloaded=api.load(po.id,actors.owner);assert.notEqual(reloaded.items.find(i=>i.id==='item-pending-a').name,'caller mutation');assert.notEqual(reloaded.events[0].reason,'caller mutation');
});
test('primary may receive another office PO but cannot revise it; closed and received items are immutable',()=>{
 const {api}=service();let po=api.load('preview-approved',actors.primary);assert.throws(()=>api.edit(po.id,'item-approved',sample(),{actor:actors.primary,key:'outside-edit',expectedVersion:po.version}),/ผู้สร้าง/);po=act(api,po,'receive',{actor:actors.primary,itemId:'item-approved',confirmed:true});assert.equal(po.items.find(i=>i.id==='item-approved').state,'received');assert.throws(()=>act(api,po,'return_edit',{reason:'แก้ไข'}),/สถานะเปลี่ยน/);assert.throws(()=>api.edit(po.id,'item-approved',sample(),{actor:actors.office,key:'received-edit',expectedVersion:po.version}),/ยังไม่ได้รับอนุญาต/);
 let close=api.load('preview-closed',actors.owner);assert.throws(()=>act(api,close,'reject',{itemId:'item-closed',reason:'เปลี่ยน'}),/PO ปิดแล้ว/);
});
test('all-rejected values are excluded; a mixed PO reports only approved and received confirmed rows',()=>{
 const {api}=service();const report=api.report(baseMonth,actors.primary);const rejected=report.rows.find(po=>po.id==='preview-all-rejected'),mixed=report.rows.find(po=>po.id==='preview-mixed');assert.equal(rejected.confirmed_purchase_cents,0);assert.equal(rejected.status,'rejected');assert.ok(mixed.items.some(i=>i.state==='approved'));assert.ok(mixed.items.some(i=>i.state==='received'));assert.ok(mixed.items.some(i=>i.state==='pending'));assert.equal(mixed.confirmed_purchase_cents,mixed.items.filter(isConfirmedPurchase).reduce((n,i)=>n+i.total_cents,0));assert.equal(report.total_cents,report.eligible.reduce((n,x)=>n+x.item.total_cents,0));assert.ok(report.budget_authorized_cents>0);
});
test('failed local persistence does not commit a partial mutation or success result',()=>{
 const store=new MemoryStorage(),api=createPreviewService({storage:store,fixtures:createPreviewFixtures()}),po=api.load('preview-pending',actors.owner),before=store.getItem(api.storageKey);store.fail=true;assert.throws(()=>api.run(po.id,'approve',{actor:actors.owner,itemId:'item-pending-a',key:'write-fail',expectedVersion:po.version}),/quota/);store.fail=false;assert.equal(store.getItem(api.storageKey),before);assert.equal(api.load(po.id,actors.owner).version,po.version);assert.equal(api.load(po.id,actors.owner).items.find(i=>i.id==='item-pending-a').state,'pending');
});
