import test from 'node:test';
import assert from 'node:assert/strict';
import {config} from '../dist/config.js';
import {api} from '../dist/api.js';

const hash='#access_token=recovery-token&refresh_token=never-persist&type=recovery&expires_in=3600';
async function fixture(run,{role='owner',invalid=false,putStatus=200}={}){
 const oldFetch=globalThis.fetch,oldStorage=globalThis.localStorage,oldNow=Date.now,oldUrl=config.supabaseUrl,oldKey=config.publishableKey;
 const calls=[],storage=[];config.supabaseUrl='https://example.supabase.co';config.publishableKey='public-key';
 globalThis.localStorage={getItem(){storage.push('get');return null;},setItem(){storage.push('set');},removeItem(){storage.push('remove');}};
 globalThis.fetch=async(url,init)=>{calls.push({url,init,body:init.body?JSON.parse(init.body):null});if(url.includes('/functions/'))return Response.json({success:true});if(url.includes('/profiles?'))return Response.json([{id:'owner-id',role}]);if(init.method==='PUT')return Response.json({id:'owner-id'},{status:putStatus});if(url.includes('/logout'))return new Response(null,{status:204});return Response.json(invalid?{message:'invalid'}:{id:'owner-id'},{status:invalid?401:200});};
 try{await run({calls,storage});}finally{api.cancelOwnerRecovery();globalThis.fetch=oldFetch;globalThis.localStorage=oldStorage;Date.now=oldNow;config.supabaseUrl=oldUrl;config.publishableKey=oldKey;}
}
test('recovery request normalizes alias without exposing passwords or recipient',async()=>fixture(async({calls})=>{await api.requestOwnerRecovery(' Nitwadee ');assert.deepEqual(calls[0].body,{action:'request-recovery',username:'nitwadee'});assert.equal(calls[0].init.headers.Authorization,undefined);}));
test('malformed and non-recovery hashes never send bearer credentials',async()=>fixture(async({calls})=>{for(const value of ['','#type=signup&access_token=x&expires_in=3600','#type=recovery&expires_in=3600','#type=recovery&access_token=x&expires_in=-1','#type=recovery&access_token=x&expires_in=nope','#type=recovery&access_token=x&expires_in=3600&error=expired'])assert.equal(await api.beginOwnerRecovery(value),false);assert.equal(calls.length,0);}));
test('recovery verifies Auth and owner profile with recovery bearer but never persists tokens',async()=>fixture(async({calls,storage})=>{assert.equal(await api.beginOwnerRecovery(hash),true);assert.equal(calls.length,2);assert.match(calls[0].url,/\/auth\/v1\/user$/);assert.match(calls[1].url,/id=eq.owner-id&role=eq.owner&deleted_at=is.null/);for(const call of calls){assert.equal(call.init.headers.Authorization,'Bearer recovery-token');assert.equal(call.init.headers.apikey,'public-key');}assert.deepEqual(storage,[]);}));
test('office profile cannot use owner recovery',async()=>fixture(async({calls})=>{assert.equal(await api.beginOwnerRecovery(hash),false);await assert.rejects(()=>api.resetOwnerRecovery('new-password'),/ลิงก์หมดอายุ/);assert.equal(calls.some(c=>c.init.method==='PUT'),false);},{role:'office'}));
test('invalid Auth recovery token fails before profile lookup and reset',async()=>fixture(async({calls})=>{await assert.rejects(()=>api.beginOwnerRecovery(hash),/ลิงก์ใช้ไม่ได้/);assert.equal(calls.length,1);await assert.rejects(()=>api.resetOwnerRecovery('new-password'),/ลิงก์หมดอายุ/);},{invalid:true}));
test('password minimum and cancellation stop reset before mutation',async()=>fixture(async({calls})=>{assert.equal(await api.beginOwnerRecovery(hash),true);await assert.rejects(()=>api.resetOwnerRecovery('12345'),/6/);api.cancelOwnerRecovery();await assert.rejects(()=>api.resetOwnerRecovery('123456'),/ลิงก์หมดอายุ/);assert.equal(calls.some(c=>c.init.method==='PUT'),false);}));
test('expired recovery remains unusable without another valid link',async()=>fixture(async({calls})=>{const now=Date.now();assert.equal(await api.beginOwnerRecovery(hash),true);Date.now=()=>now+3601000;await assert.rejects(()=>api.resetOwnerRecovery('123456'),/ลิงก์หมดอายุ/);assert.equal(calls.some(c=>c.init.method==='PUT'),false);}));
test('reset uses Auth password endpoint only, clears session and globally signs out',async()=>fixture(async({calls,storage})=>{assert.equal(await api.beginOwnerRecovery(hash),true);await api.resetOwnerRecovery('123456');const put=calls.find(c=>c.init.method==='PUT');assert.deepEqual(put.body,{password:'123456'});assert.match(put.url,/\/auth\/v1\/user$/);assert.equal(put.init.headers.Authorization,'Bearer recovery-token');assert.equal(put.init.headers.apikey,'public-key');assert.match(calls.at(-1).url,/logout\?scope=global$/);assert.deepEqual(storage,['remove']);await assert.rejects(()=>api.resetOwnerRecovery('abcdef'),/ลิงก์หมดอายุ/);}));
test('Auth rejection does not claim reset success or store password',async()=>fixture(async({storage,calls})=>{assert.equal(await api.beginOwnerRecovery(hash),true);await assert.rejects(()=>api.resetOwnerRecovery('123456'));assert.equal(calls.filter(c=>c.init.method==='PUT').length,1);assert.deepEqual(storage,[]);},{putStatus:400}));
