-- READ ONLY. Replace __SOURCE_PROJECT_REF__ metadata only after validating the connected project.
-- Result includes credential hashes: do not print/commit; encrypt with a separately stored key.
-- One SELECT captures public application rows + whitelisted permanent Auth fields.
with application as (select jsonb_build_object('project_ref','__SOURCE_PROJECT_REF__','captured_at',now(),'snapshot',txid_current_snapshot()::text,'postgres_version',version(),'scope','PO application and permanent email-password account snapshot; excludes live sessions, Storage file bytes, secrets and dashboard settings','tables',jsonb_build_object('departments',(select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text),'[]'::jsonb) from public.departments t),'profiles',(select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text),'[]'::jsonb) from public.profiles t),'purchase_orders',(select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text),'[]'::jsonb) from public.purchase_orders t),'po_items',(select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text),'[]'::jsonb) from public.po_items t),'po_events',(select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text),'[]'::jsonb) from public.po_events t),'notifications',(select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text),'[]'::jsonb) from public.notifications t),'po_commands',(select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text),'[]'::jsonb) from public.po_commands t)),
'sequence_state',(select jsonb_build_object('name','po_number_seq','last_value',last_value,'is_called',is_called) from public.po_number_seq),
'sequences',(select coalesce(jsonb_agg(to_jsonb(t)),'[]'::jsonb) from pg_sequences t where schemaname='public'),
'columns',(select jsonb_agg(to_jsonb(t) order by table_name,ordinal_position) from information_schema.columns t where table_schema='public'),
'constraints',(select jsonb_agg(jsonb_build_object('table',c.relname,'name',con.conname,'definition',pg_get_constraintdef(con.oid))) from pg_constraint con join pg_class c on con.conrelid=c.oid join pg_namespace n on c.relnamespace=n.oid where n.nspname='public'),
'functions',(select jsonb_agg(jsonb_build_object('name',p.proname,'definition',pg_get_functiondef(p.oid))) from pg_proc p join pg_namespace n on p.pronamespace=n.oid where n.nspname='public' and p.prokind='f'),
'policies',(select jsonb_agg(to_jsonb(t)) from pg_policies t where schemaname='public'),
'indexes',(select jsonb_agg(to_jsonb(t)) from pg_indexes t where schemaname='public'),
'triggers',(select jsonb_agg(jsonb_build_object('table',c.relname,'definition',pg_get_triggerdef(t.oid))) from pg_trigger t join pg_class c on t.tgrelid=c.oid join pg_namespace n on c.relnamespace=n.oid where n.nspname='public' and not t.tgisinternal),
'grants',(select jsonb_agg(to_jsonb(t)) from information_schema.role_table_grants t where table_schema='public')
) as backup) select backup || jsonb_build_object('auth_scope','email-password accounts only; no session, refresh, recovery, confirmation or change tokens','auth_users',(select coalesce(jsonb_agg(to_jsonb(u) order by id),'[]'::jsonb) from (select instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,invited_at,last_sign_in_at,raw_app_meta_data,raw_user_meta_data,is_super_admin,created_at,updated_at,phone,phone_confirmed_at,banned_until,is_sso_user,deleted_at,is_anonymous from auth.users) u),'auth_identities',(select coalesce(jsonb_agg(to_jsonb(i) order by id),'[]'::jsonb) from (select provider_id,user_id,identity_data,provider,last_sign_in_at,created_at,updated_at,id from auth.identities) i)) as backup from application;
